version = 0.1

[default.deploy.parameters]
stack_name = "gharkakhana-dev"
resolve_s3 = true
s3_prefix = "gharkakhana"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=dev"

[default.build.parameters]
cached = true
parallel = true

[staging.deploy.parameters]
stack_name = "gharkakhana-staging"
resolve_s3 = true
s3_prefix = "gharkakhana-staging"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=staging"

[prod.deploy.parameters]
stack_name = "gharkakhana-prod"
resolve_s3 = true
s3_prefix = "gharkakhana-prod"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=prod"
